// Code generated by gsx; DO NOT EDIT.

package main

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/livetx/livetx/internal/audio"
	"github.com/livetx/livetx/ui"
	_gsxio "io"
)

//line page.gsx:8:1
// Page is the full LiveTX web UI, rendered server-side with gsxui components.
// Interactivity (device start/stop, live transcript over WebSocket) is driven
// by /app.js; styling comes from the compiled /app.css.

//line page.gsx:11:1
func Page(devices []audio.Device) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line page.gsx:12:2
		_gsxgw.S("<html lang=\"en\" class=\"dark\">")
//line page.gsx:13:3
		_gsxgw.S("<head>")
//line page.gsx:14:4
		_gsxgw.S("<meta charset=\"utf-8\">")
//line page.gsx:15:4
		_gsxgw.S("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
//line page.gsx:16:4
		_gsxgw.S("<title>LiveTX</title>")
//line page.gsx:17:4
		_gsxgw.S("<link rel=\"stylesheet\" href=\"/app.css\"></head>")
//line page.gsx:19:3
		_gsxgw.S("<body class=\"overflow-hidden bg-background text-foreground flex flex-col\" style=\"height:100vh\">")
//line page.gsx:20:4
		_gsxgw.S("<header class=\"flex shrink-0 flex-wrap items-center gap-3 border-b border-border bg-card px-4 py-3\">")
//line page.gsx:21:5
		_gsxgw.S("<div class=\"mr-auto flex items-center gap-2 font-semibold tracking-wide\">")
//line page.gsx:22:6
		_gsxgw.S("<span id=\"dot\" class=\"inline-block size-2 rounded-full bg-muted-foreground\"></span>LiveTX</div>")
//line page.gsx:26:5
		_gsxgw.Node(ctx, ui.Label(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Device")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "for", Value: "device"}}))
//line page.gsx:27:5
		_gsxgw.Node(ctx, ui.NativeSelect(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line page.gsx:28:6
			if len(devices) == 0 {
//line page.gsx:29:7
				_gsxgw.Node(ctx, ui.NativeSelectOption("", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("No devices found")
					return _gsxgw.Err()
				}), nil))
			} else {
//line page.gsx:31:7
				for _, d := range devices {
//line page.gsx:32:8
					_gsxgw.Node(ctx, ui.NativeSelectOption(d.ID, false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line page.gsx:32:44
						_gsxgw.Text(string(d.Name))
						return _gsxgw.Err()
					}), nil))
				}
			}
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "id", Value: "device"}}, _gsxrt.Attrs{{Key: "class", Value: "min-w-56"}})))
//line page.gsx:37:5
		_gsxgw.Node(ctx, ui.Label(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("In")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "for", Value: "langIn"}}))
//line page.gsx:38:5
		_gsxgw.S("<input id=\"langIn\" value=\"auto\" class=\"h-8 w-16 rounded-lg border border-input bg-transparent px-2.5 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 dark:bg-input/30\">")
//line page.gsx:40:5
		_gsxgw.Node(ctx, ui.Label(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Out")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "for", Value: "langOut"}}))
//line page.gsx:41:5
		_gsxgw.S("<input id=\"langOut\" value=\"en\" class=\"h-8 w-16 rounded-lg border border-input bg-transparent px-2.5 text-sm outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 dark:bg-input/30\">")
//line page.gsx:44:5
		_gsxgw.Node(ctx, ui.Button("", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Start")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "id", Value: "toggle"}}))
		_gsxgw.S("</header>")
//line page.gsx:47:4
		_gsxgw.S("<main class=\"flex-1 overflow-y-auto px-5 py-6\" style=\"min-height:0\">")
//line page.gsx:48:5
		_gsxgw.S("<div id=\"transcript\" class=\"mx-auto max-w-3xl space-y-2.5\">")
//line page.gsx:49:6
		_gsxgw.S("<p class=\"mt-10 text-center text-muted-foreground\">Pick a device and press Start.</p></div></main>")
//line page.gsx:53:4
		_gsxgw.S("<footer class=\"flex shrink-0 items-center gap-3 border-t border-border bg-card px-4 py-2\">")
//line page.gsx:54:5
		_gsxgw.Node(ctx, ui.Badge("secondary", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Ready")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "id", Value: "status"}}))
//line page.gsx:55:5
		_gsxgw.Node(ctx, ui.Button("outline", "sm", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Auto-scroll: On")
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "id", Value: "autoscroll"}}, _gsxrt.Attrs{{Key: "class", Value: "ml-auto"}})))
		_gsxgw.S("</footer>")
//line page.gsx:58:4
		_gsxgw.S("<script src=\"/app.js\"")
		_gsxgw.Nonce(ctx)
		_gsxgw.S("></script></body></html>")
		return _gsxgw.Err()
	})
}
