// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxcm "github.com/livetx/livetx/ui/merge"
	_gsxio "io"
)

//line badge.gsx:5:1
// Badge is the shadcn/ui Badge. variant: "" (default) | "secondary" |
// "destructive" | "outline" | "ghost" | "link". Extra attributes fall
// through to the <span>; caller classes merge (caller wins per property).
//
// Retargeted to nova density (2026-07-24 nova density map, `## badge`).
// ADAPT: nova keys directional icon padding off `data-icon="inline-start|
// inline-end"` stamps this component doesn't emit; ported instead onto
// gsxui's existing has-[>svg]:px-* selector mechanism (the same
// substitution button.gsx/toggle.gsx make — see their own doc comments),
// collapsing nova's matching inline-start/inline-end value (both px-1.5)
// into one has-[>svg]:px-1.5.

//line badge.gsx:16:1
func Badge(variant string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line badge.gsx:17:2
		_gsxgw.S("<span")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"badge\"")
		}
		if !attrs.Has("data-variant") {
			_gsxgw.S(" data-variant=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
			_gsxgw.S("\"")
		}
		_gsxv0 := "inline-flex h-5 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-4xl border border-transparent px-2 py-0.5 text-xs font-medium whitespace-nowrap transition-[color,box-shadow] has-[>svg]:px-1.5 focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none [&>svg]:size-3!"
		var _gsxv1 string
		switch variant {
		case "secondary":
			_gsxv1 = "bg-secondary text-secondary-foreground [a&]:hover:bg-secondary/90"
		case "destructive":
			_gsxv1 = "bg-destructive text-white focus-visible:ring-destructive/20 dark:bg-destructive/60 dark:focus-visible:ring-destructive/40 [a&]:hover:bg-destructive/90"
		case "outline":
			_gsxv1 = "border-border text-foreground [a&]:hover:bg-accent [a&]:hover:text-accent-foreground"
		case "ghost":
			_gsxv1 = "[a&]:hover:bg-accent [a&]:hover:text-accent-foreground"
		case "link":
			_gsxv1 = "text-primary underline-offset-4 [a&]:hover:underline"
		default:
			_gsxv1 = "bg-primary text-primary-foreground [a&]:hover:bg-primary/90"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(_gsxv0), _gsxrt.Class(_gsxv1), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line badge.gsx:39:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</span>")
		return _gsxgw.Err()
	})
}
