// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/livetx/livetx/ui/merge"
	_gsxio "io"
)

//line label.gsx:5:1
// Label is the shadcn/ui Label. shadcn wraps Radix's LabelPrimitive.Root,
// which renders a plain <label> with an onMouseDown guard that suppresses
// double-click text selection; gsx ports the markup straight (base class
// already carries select-none, so the JS guard's effect is redundant here —
// see docs/jsx-parity.md).

//line label.gsx:10:1
func Label(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line label.gsx:11:2
		_gsxgw.S("<label")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"label\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line label.gsx:16:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</label>")
		return _gsxgw.Err()
	})
}
