// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxcm "github.com/livetx/livetx/ui/merge"
	_gsxio "io"
)

//line separator.gsx:5:1
// Separator is the shadcn/ui Separator. orientation: "" (default,
// "horizontal") | "vertical" — stamped onto data-orientation, which one
// verbatim class string dispatches on via Tailwind's data-[orientation=...]
// selectors, so no variant switch is needed. Radix's decorative prop (its
// default true) is not ported — see docs/jsx-parity.md.

//line separator.gsx:10:1
func Separator(orientation string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line separator.gsx:11:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"separator\"")
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"none\"")
		}
		if !attrs.Has("data-orientation") {
			_gsxgw.S(" data-orientation=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((orientation), "horizontal")))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S("></div>")
		return _gsxgw.Err()
	})
}
